#!/bin/sh

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ "$PWD" != "$SCRIPT_DIR" ]
then
  echo This script must be called from its own directory
  exit 7
fi


if [ -z "$EPL_SHELL" ]
then
  echo This script must be run inside eden platform shell.nix shell
  exit 7
fi

export EPL_PROJECT="${EPL_PROJECT:-single-dc}"
export EPL_ROOT_DIR="$(cd ..; pwd)"
export EPL_EXECUTABLE=$EPL_ROOT_DIR/target/debug/epl

for EPL_PROJECT in envs/*
do
	pushd $EPL_PROJECT
	make compile-project
	popd
done
